"""Overlay A/B/C/D labels on sb-05_05.png arrows for the summative quiz.

Source: img/storyboard/sb-05_05.png (1536x1024, generated by AI).
Output: img/storyboard/sb-05_05_labeled.png (same dims + 4 labels).

Arrow taxonomy (clockwise from top, marker at upper-right of contour basin):
- A = up-right arrow   = sign-flip (uphill, perpendicular-but-outward)
- B = horizontal-right = tangent to contour (perpendicular ≠ descent)
- C = down-right       = oblique at ~45° (descends but not steepest)
- D = down-left        = steepest descent (perpendicular-inward to minimum, CORRECT)

Re-run after regenerating sb-05_05.png with the new storyboard prompt;
adjust tip coordinates if marker/arrow positions shift.
"""
from PIL import Image, ImageDraw, ImageFont
from pathlib import Path

SRC = Path("img/storyboard/sb-05_05.png")
OUT = Path("img/storyboard/sb-05_05_labeled.png")
DEBUG = Path("dev/sb-05_05_labeled_debug.png")

# Tip coordinates (full-image px) — measured from dev/sb-05_05-arrows-zoom.png
# Marker centre ≈ (1025, 567)
TIPS = {
    "A": (1117, 508),  # up-right
    "B": (1300, 567),  # horizontal-right
    "C": (1293, 660),  # down-right
    "D": (950,  633),  # down-left
}
# Label offset = small push past the tip in the arrow direction, so the
# letter sits next to (not on) the arrowhead.
OFFSETS = {
    "A": (+25, -55),
    "B": (+30, -25),
    "C": (+25, +15),
    "D": (-55, +15),
}

FONT_PATH = "C:/Windows/Fonts/arialbd.ttf"
FONT_SIZE = 62
FILL = (255, 255, 255)        # white text
STROKE = (0, 0, 0)            # black outline for legibility on warm/dark
STROKE_W = 4


def render(debug: bool) -> None:
    im = Image.open(SRC).convert("RGBA")
    draw = ImageDraw.Draw(im)
    font = ImageFont.truetype(FONT_PATH, FONT_SIZE)
    for label, (tx, ty) in TIPS.items():
        ox, oy = OFFSETS[label]
        draw.text(
            (tx + ox, ty + oy),
            label,
            font=font,
            fill=FILL,
            stroke_width=STROKE_W,
            stroke_fill=STROKE,
        )
        if debug:
            r = 8
            draw.ellipse((tx - r, ty - r, tx + r, ty + r), outline=(0, 255, 0), width=3)
    target = DEBUG if debug else OUT
    target.parent.mkdir(parents=True, exist_ok=True)
    im.convert("RGB").save(target)
    print(f"wrote {target} ({im.size})")


if __name__ == "__main__":
    render(debug=True)
    render(debug=False)
